# Generated by Django 5.2a1 on 2025-02-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En tránsito'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('EN_PREPARACION', 'En preparación'), ('LISTO_PARA_RETIRO', 'Listo para retiro')], default='PENDIENTE', max_length=20)),
                ('opcion_entrega', models.CharField(choices=[('RETIRO_SUCURSAL', 'Retiro en Sucursal'), ('ENVIO_DESTINO', 'Envío a Sucursal de Destino')], default='RETIRO_SUCURSAL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
